# Site
name: 'Brooke K. Ryan'
description: 'Personal website and blog.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/brooke_ghostie.png'
url: 'https://brookekryan.com'
baseurl: ''
disqus: 'brookekryan'
email: 'brookekelseyryan@gmail.com'
#mailchimp-list: 'https://gmail.us5.list-manage.com/subscribe/post?u=f32b0a0ea962798e8943cb136&amp;id=e707e08ea3'

include: [ "_pages" ]
permalink: /:title/

destination: ./docs

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-scholar

author: brooke

authors:
  brooke:
    name: "Brooke K. Ryan"
    avatar: "assets/images/brooke_avatar.jpg"
    bio: "I'm currently a graduate student at UC Irvine pursuing my master's in Computer Science. My goal is to increase accessibility in Artificial Intelligence and Computer Science more broadly."
    long_bio: "I'm currently a graduate student at UC Irvine pursuing my master's in Computer Science. My goal is to increase accessibility in Artificial Intelligence and Computer Science more broadly. Generally, I write about things that I wish I knew or things I find important enough to teach or talk about—this can range from topics on introductory software engineering, tutorials related to courses I've taught, navigating tools for neural networks research, and anything in between. I'm also really passionate about helping increase underrepresented groups in Computer Science—whether that's women, queer folks, people of color, or people with disabilities. My goal is to reignite the joy of science and the process of discovery for anyone who has ever thought they weren't good enough to do so!"
    email: brooke.ryan@uci.edu

collections:
  publications:
    output: true
  projects:
    output: true
  teaching:
    output: true
  media:
    output: false

# Defaults
defaults:

  # all _posts
  - scope:
      path: "_posts/"
    values:
      layout: post
      avatar: /assets/images/avatar1.jpg

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Syntax
markdown: kramdown
highlighter: rouge

# Scholar
scholar:
  style: custom


# Paginate
#gems: [jekyll-paginate]
paginate: 20
paginate_path: "/writing/page:num"




# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [ README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules ]